# Generated by Django 6.1.1 on 2026-09-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='notificado',
            field=models.BooleanField(default=False),
        ),
    ]
