# Generated by Django 6.1.1 on 2026-09-06 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Camiseta Oversize', max_length=120)),
                ('descripcion', models.TextField(help_text='Descripcion detallada de la prenda')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en bolivianos (Bs)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('imagen', models.ImageField(blank=True, help_text='Foto de la prenda', null=True, upload_to='productos/')),
                ('categoria', models.CharField(choices=[('mujer', 'Mujer'), ('hombre', 'Hombre'), ('ninos', 'Ninos'), ('calzado', 'Calzado'), ('accesorios', 'Accesorios'), ('abrigos', 'Abrigos')], default='mujer', max_length=20)),
                ('tallas', models.CharField(help_text='Separadas por comas. Ej: M, L, XL', max_length=200)),
                ('colores', models.CharField(help_text='Separados por comas. Ej: Negro, Blanco', max_length=200)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad disponible. 0 = AGOTADO')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar oculta el producto de la tienda sin borrarlo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-creado'],
            },
        ),
    ]
